#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Given a list of numbers, 
determine and print the number of elements t
hat are greater than both of their neighbors.

The first and the last items of the list
 shouldn't be considered because they 
 don't have two neighbors.
 
 
@author: nat
"""

a_list = [int(str_numbers) for str_numbers in input().split()]
total = [i for i in range(1, len(a_list) - 1) if a_list[i - 1] < a_list[i] > a_list[i + 1]]
print(len(total))